2024-11-08 17:56:55 [INFO] Correct path: data/sample_data.pcd
2024-11-08 17:56:55 [INFO] Successfully read pcd_file from data/sample_data.pcd
2024-11-08 17:56:55 [ERROR] Main Using the wrong typeerror--> remove_statistical_outlier(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.PointCloud, nb_neighbors: int, std_ratio: float, print_progress: bool = False) -> Tuple[open3d.cpu.pybind.geometry.PointCloud, List[int]]

Invoked with: PointCloud with 460400 points.; kwargs: nb_neighbors='20', std_ratio=2.0
Traceback (most recent call last):
  File "C:\Users\jomar\Desktop\image_processing-main\main.py", line 17, in main
    img_3d: o3d.geometry.PointCloud = dp.remove_noise(
                                      ^^^^^^^^^^^^^^^^
  File "C:\Users\jomar\Desktop\image_processing-main\data_processing.py", line 22, in remove_noise
    cl, ind = pcd.remove_statistical_outlier(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: remove_statistical_outlier(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.PointCloud, nb_neighbors: int, std_ratio: float, print_progress: bool = False) -> Tuple[open3d.cpu.pybind.geometry.PointCloud, List[int]]

Invoked with: PointCloud with 460400 points.; kwargs: nb_neighbors='20', std_ratio=2.0
2024-11-08 17:56:55 [ERROR] [__main__] [<module>] Check the type error--> remove_statistical_outlier(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.PointCloud, nb_neighbors: int, std_ratio: float, print_progress: bool = False) -> Tuple[open3d.cpu.pybind.geometry.PointCloud, List[int]]

Invoked with: PointCloud with 460400 points.; kwargs: nb_neighbors='20', std_ratio=2.0
Traceback (most recent call last):
  File "C:\Users\jomar\Desktop\image_processing-main\main.py", line 17, in main
    img_3d: o3d.geometry.PointCloud = dp.remove_noise(
                                      ^^^^^^^^^^^^^^^^
  File "C:\Users\jomar\Desktop\image_processing-main\data_processing.py", line 22, in remove_noise
    cl, ind = pcd.remove_statistical_outlier(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: remove_statistical_outlier(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.PointCloud, nb_neighbors: int, std_ratio: float, print_progress: bool = False) -> Tuple[open3d.cpu.pybind.geometry.PointCloud, List[int]]

Invoked with: PointCloud with 460400 points.; kwargs: nb_neighbors='20', std_ratio=2.0
2024-11-08 17:57:25 [INFO] Correct path: data/sample_data.pcd
2024-11-08 17:57:25 [INFO] Successfully read pcd_file from data/sample_data.pcd
2024-11-08 17:57:25 [ERROR] [__main__] [<module>] Check the type error--> remove_statistical_outlier(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.PointCloud, nb_neighbors: int, std_ratio: float, print_progress: bool = False) -> Tuple[open3d.cpu.pybind.geometry.PointCloud, List[int]]

Invoked with: PointCloud with 460400 points.; kwargs: nb_neighbors='20', std_ratio=2.0
Traceback (most recent call last):
  File "C:\Users\jomar\Desktop\image_processing-main\main.py", line 17, in main
    img_3d: o3d.geometry.PointCloud = dp.remove_noise(
                                      ^^^^^^^^^^^^^^^^
  File "C:\Users\jomar\Desktop\image_processing-main\data_processing.py", line 22, in remove_noise
    cl, ind = pcd.remove_statistical_outlier(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: remove_statistical_outlier(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.PointCloud, nb_neighbors: int, std_ratio: float, print_progress: bool = False) -> Tuple[open3d.cpu.pybind.geometry.PointCloud, List[int]]

Invoked with: PointCloud with 460400 points.; kwargs: nb_neighbors='20', std_ratio=2.0
2024-11-08 17:58:04 [INFO] Correct path: data/sample_data.pcd
2024-11-08 17:58:04 [INFO] Successfully read pcd_file from data/sample_data.pcd
2024-11-08 17:58:04 [ERROR] [__main__] Check the type error--> remove_statistical_outlier(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.PointCloud, nb_neighbors: int, std_ratio: float, print_progress: bool = False) -> Tuple[open3d.cpu.pybind.geometry.PointCloud, List[int]]

Invoked with: PointCloud with 460400 points.; kwargs: nb_neighbors='20', std_ratio=2.0
Traceback (most recent call last):
  File "C:\Users\jomar\Desktop\image_processing-main\main.py", line 17, in main
    img_3d: o3d.geometry.PointCloud = dp.remove_noise(
                                      ^^^^^^^^^^^^^^^^
  File "C:\Users\jomar\Desktop\image_processing-main\data_processing.py", line 22, in remove_noise
    cl, ind = pcd.remove_statistical_outlier(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: remove_statistical_outlier(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.cpu.pybind.geometry.PointCloud, nb_neighbors: int, std_ratio: float, print_progress: bool = False) -> Tuple[open3d.cpu.pybind.geometry.PointCloud, List[int]]

Invoked with: PointCloud with 460400 points.; kwargs: nb_neighbors='20', std_ratio=2.0
2024-11-08 18:01:34 [INFO] Correct path: data/sample_data.pcd
2024-11-08 18:01:34 [INFO] Successfully read pcd_file from data/sample_data.pcd
2024-11-08 18:01:35 [INFO] Number of points after noise removal: 456450
2024-11-08 18:01:35 [INFO] Number of projected points: 456450
2024-11-08 18:01:35 [INFO] Calculated to max depth 0.929669976234436, min depth -1.1238000392913818
2024-11-08 18:01:35 [INFO] Depth map parameters: 10000, 
2024-11-08 18:01:35 [ERROR] [ConfigFileManager] [save_image] Directory does not exist: 
2024-11-08 18:01:35 [ERROR] Depth map can't saved
2024-11-08 18:01:35 [INFO] Calculated to max depth 0.929669976234436, min depth -1.1238000392913818
2024-11-08 18:01:35 [INFO] Heat map parameters: 30000, data/heat_map.png
2024-11-08 18:01:35 [INFO] Correct path: data/heat_map.png
2024-11-08 18:01:35 [INFO] Heat map saved at data/heat_map.png
